### PR TITLE
Keycloak v 17+ update and bug fix

### PR DESCRIPTION
**Pull request by gterdem**
Update to Keycloak 17+
fixes https://github.com/AnderssonPeter/Keycloak.Net/issues/2
fixes https://github.com/lvermeulen/Keycloak.Net/issues/71

Tested in keycloak 19.0.2

### CODE REVIEW

**Comment by gterdem** [comment]
@AnderssonPeter 
Can you publish a new NuGet version when you merge it, please?

**Comment by AnderssonPeter** [comment]
I see that you have modified the auth url, will this break compatibility with older versions of keycloak?

And Keycloak.Net.Models.ProtocolMappers.Config is not not used so could you remove that class?

**Comment by gterdem** [comment]
> I see that you have modified the auth url, will this break compatibility with older versions of keycloak?
> 
> And Keycloak.Net.Models.ProtocolMappers.Config is not not used so could you remove that class?

I have added `KeycloakOptions` for configuring the prefix and the default `adminClientId`.

It will be a breaking change for older versions since `/auth` prefix is no longer used and it's default value is `""`. 
To use it with **older versions**, `KeycloakClient` should be instantiated as:
```cs
new KeycloakClient(
          "http://keycloak.url",
          "adminUserName",
          "adminPassword",
          new KeycloakOptions("auth")
      );
```

**Comment by AnderssonPeter** [comment]
New nuget has been uploaded

**Pull request merged**
