### PR TITLE
Upgrade libs kc17

### PR DESCRIPTION
**Pull request by psavva**

### CODE REVIEW

**Comment by psavva** [comment]
@AnderssonPeter   Any feedback, can you get this merged?

**Comment by AnderssonPeter** [comment]
Sorry for the late reply, I must have missed the email notifying me of this pull request.

Did Flurl.Http have a breaking change that is causing all the ResponseMessage changes?

Also there seems to be a lot of conflicts, could you fix those?

**Comment by psavva** [comment]
Thanks for getting back to me.

I'll merge your changes, and republish.  No issue.

Fluro has breaking charges, yes

**Comment by AnderssonPeter** [comment]
@psavva any news?

**Comment by psavva** [comment]
I'm out of the country and will return late January.

I'll resubmit the PR on my return.

Looking forward to helping support this library.

Best Regards
Panayiotis Savva

**Comment by psavva** [comment]
closing this PR and will open a new one with changes needed for the upgrade in separate PRs

**Pull request closed without merging**
